apiVersion: v1
kind: Service
metadata:
  name: cre8-web-service
  namespace: prod
spec:
  selector:
    app: cre8-web
  type: NodePort
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
  - name: cre8-web-service-port
    protocol: TCP
    port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30115
